#Spring configuration
spring:
#Datasource
  datasource:
    name: testdb
    url: jdbc:h2:mem:testdb
    platform: h2
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /console

# Logging
logging:
  level:
    root: ERROR
    org.springframework: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.bfh.springbootsecurity: DEBUG


